name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # update every hour
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kelomo2502
          base: activity, community, repositories, metadata
          config_timezone: Africa/Lagos
